import Head from 'next/head';
import Link from "next/link";
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-300  text-purple-900 text-5xl p-64">
اینجا زومیلا است
       <Link href={"../pages/post/Post"}> سلام</Link>
      </main>


    </div>
  )
}
