import Head from 'next/head';
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="bg-zoomila_bg w-screen h-auto flex flex-col">
                <div className="w-screen h-16 bg-green_accent flex justify-center">
                    <div className="w-5/6 h-16 flex text-white items-center">
                        <ul className="flex flex-row space-x-8 text-lg">
                            <li className="flex flex-row items-center">همه املاک
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path fillrule="evenodd"
                                          d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                          cliprule="evenodd"/>
                                </svg>
                            </li>
                            <li className="pr-8 flex flex-row items-center">تعداد اتاق
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path fillRule="evenodd"
                                          d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                          clipRule="evenodd"/>
                                </svg>
                            </li>
                            <li className="flex flex-row items-center">متراژ
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path fillRule="evenodd"
                                          d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                          clipRule="evenodd"/>
                                </svg>
                            </li>
                            <li className="flex flex-row items-center">قیمت
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path fillRule="evenodd"
                                          d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                          clipRule="evenodd"/>
                                </svg>
                            </li>
                            <li className="flex flex-row items-center">امکانات
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path fillRule="evenodd"
                                          d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                          clipRule="evenodd"/>
                                </svg>
                            </li>
                            <li className="text-filter_color">پاک کردن فیلتر</li>
                        </ul>
                    </div>
                </div>
                <div className="w-screen h-auto flex justify-center">
                    <div className="w-5/6 h-auto flex flex-col">
                        <div className="flex flex-row justify-between w-full h-auto ">
                            <div className="w-72% h-92 my-4">
                                <div className="w-full h-16 rounded-sm border border-black flex flex-row">

                                </div>
                            </div>
                            <div className="w-1/4 h-92 my-4">
                                <div className="w-full h-16 rounded-sm border border-black flex flex-row items-center justify-between px-4 bg-white">
                                    <input type="text" placeholder="جستجو بر اساس کد آگهی" className="border-none focus:border-none focus:outline-0"/>
                                    <div>
                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none"
                                             viewBox="0 0 24 24" stroke="currentColor">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                                                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="bg-white flex flex-col w-full text-city_explain text-md leading-7 p-3 rounded-b-sm mb-8">
                            <p className="text-justify">
                                شهر تهران با سابقه دویست ساله پایتختی خود و همچنین با داشتن 22 منطقه شهری، بزرگترین شهر کشور است . علی رقم تمام شلوغی های این شهر بزرگ، تهران یکی از بزرگترین قطب های گردشگری کشور است. از طرفی بهترین و معروفترین مراکز آموزشی نظیر دانشگاه شهید بهشتی، دانشگاه صنعتی شریف و... در این شهر واقع شده اند. و طبق آخرین سرشماری در سال 95، تهران جمعیتی بیش از 8 میلیون نفر دارد.
                            </p>
                            <h3 className="text-lg my-3">تقسیمات منطقه ای تهران</h3>
                            <p className="text-justify">
                                محله های تهران در چهار جهت شرق، غرب، جنوب و شمال جای گرفته و از جمله مناطق مهم شمال تهران می توان به کامرانیه، زعفرانیه، قلهک و جردن اشاره کرد. همچنین محله های خراسان، خانی آباد، شوش و راه آهن هم از جمله مناطق جنوب تهران هستند.
                            </p>
                            <h2 className="text-lg my-3">قیمت خانه وآپارتمان در تهران</h2>
                            <p className="text-justify">
                                خرید خانه و آپارتمان در تهران بدلیل حجم زیاد محله و مناطقش دارای اختلاف قیمت های بالایی است. طبیعتا هر محله و منطقه ای دارای امکانات و ویژگی های بخصوصی است که سبب همین اختلافات قیمت می شود. اما بطور کلی قیمت خانه و املاک در شمال تهران بسیار گرانتر و بیشتراز مناطق جنوبی است . برای مثال قیمت خانه در زعفرانیه نسبت به قیمت خانه در تهران پارس تهران چیزی حدود  8- 9 برابر گرانتر است!
                            </p>
                            <div className="flex flex-row justify-between my-4">
                                <div className="flex flex-col  justify-between w-3/10 space-y-3">
                                    <h3>مناطق مهم تهران</h3>
                                    <hr/>
                                    <ul className="list-square list-inside marker:text-button_color">
                                        <li>برج ازادی (نماد شهر تهران است)</li>
                                        <li>بازار تجریش</li>
                                        <li>عمارت مسعودیه</li>
                                        <li>موزه های ملی نظیر موزه ملک</li>
                                        <li>آرامگاه مقدس شاه عبدالعظیم</li>
                                        <li>مجموعه بهارستان</li>
                                    </ul>
                                </div>
                                <div className="flex flex-col justify-between w-3/10 space-y-3">
                                    <h3>گرانترین محله های تهران برای خرید خانه</h3>
                                    <hr/>
                                    <ul className="list-square list-inside marker:text-button_color ">
                                        <li>زعفرانیه</li>
                                        <li>ولنجک</li>
                                        <li>کامرانیه</li>
                                        <li>اقدسیه</li>
                                        <li>قیطریه</li>
                                        <li>پونک</li>
                                    </ul>
                                </div>
                                <div className="flex flex-col justify-between w-3/10 space-y-3 ">
                                    <h3>خیابان های مهم تهران</h3>
                                    <hr/>
                                    <ul className="list-square list-inside marker:text-button_color">
                                        <li>خیابان ولیعصر</li>
                                        <li>خیابان آزادی</li>
                                        <li>خیابان فرشته</li>
                                        <li>خیابان جردن</li>
                                        <li>خیابان شریعتی</li>
                                        <li>خیابان انقلاب</li>
                                    </ul>
                                </div>
                            </div>
                            <hr/>
                            <a href="https://www.zoomila.com/blog/%d8%ae%d8%b1%db%8c%d8%af-%d8%ae%d8%a7%d9%86%d9%87-%d8%af%d8%b1-%d8%aa%d9%87%d8%b1%d8%a7%d9%86" className="text-blue_accent my-6">درباره خرید خانه در تهران بخوانید</a>
                            <hr/>
                            <div className="flex  my-6">
                                <ul className="flex flex-row space-x-2">
                                    <li>
                                        <span  className="bg-tag_gray px-4 rounded-sm hover:bg-button_color hover:text-white">خرید و فروش خانه در تهران</span>
                                    </li>
                                    <li className=" pr-2">
                                        <span  className="bg-tag_gray px-4 rounded-sm hover:bg-button_color hover:text-white">خرید و فروش آپارتمان در تهران</span>
                                    </li>
                                    <li>
                                        <span  className="bg-tag_gray px-4 rounded-sm hover:bg-button_color hover:text-white">خرید و فروش ملک در تهران</span>
                                    </li>
                                    <li>
                                        <span  className="bg-tag_gray px-4 rounded-sm hover:bg-button_color hover:text-white">خرید و فروش ویلا در تهران</span>
                                    </li>
                                    <li>
                                        <span  className="bg-tag_gray px-4 rounded-sm hover:bg-button_color hover:text-white">خرید خانه در تهران</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </main>


        </div>
    )
}
